### ISSUE TITLE
Not compatible with spigot 1.9

### ISSUE THREAD

**Issue by i-rme** [ShevchikUnsupportedProjects/DatDuplicateRemover#2]
`[19:02:51] [Server thread/INFO]: [PlayerDataDuplicateRemover] Enabling PlayerDataDuplicateRemover v2.0
[19:03:05] [Server thread/ERROR]: Error occurred while enabling PlayerDataDuplicateRemover v2.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at datduplicateremover.storage.RealPlayersStorage.<init>(RealPlayersStorage.java:44) ~[?:?]
    at datduplicateremover.DatDuplicateRemover.onEnable(DatDuplicateRemover.java:42) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

I love the plugin (because it checks the correct case of the username), please update to 1.9

**Comment by antoniobenedetti** [comment]
@Shevchik Can you please update it and compile 1.9 version?

**Comment by WebShark025** [comment]
@i-rme @antoniobenedetti Forked and fixed for 1.9&1.10: https://www.spigotmc.org/resources/playeruuidduplicateremoverreborn.28506/
